### ISSUE TITLE
pack_entitlement() not calculating correct values when pack size greater than entitlement 

### ISSUE THREAD

**Issue by timcu** [timcu/sas-select#14]
For example pack_entitlement(10, '5m') returns
'Your medicare entitlement is2pack permonth'
but should return 
'Your Medicare entitlement is 1 pack per 2 months'

**Comment by chayawit** [comment]
Should pack_entitlement(100, '60m') return 1 pack per 1 month or 2 months?
This is Company Code 37443.

**Comment by timcu** [comment]
2 months

**Comment by chayawit** [comment]
I've prepared the changes but will apply only after Annie solves https://github.com/timcu/sas-select/issues/13.

**Comment by timcu** [comment]
OK. @anniequasar we are waiting on you ;)

**Comment by timcu** [comment]
Fixed in PR #37
