### ISSUE TITLE
If user clicks 'search' without entering any criteria then the whole database is returned

### ISSUE THREAD

**Issue by timcu** [timcu/sas-select#16]
No records should be returned unless search criteria entered. Should probably limit the number of records returned (say to 20) if too broad a criteria are entered.

**Comment by chayawit** [comment]
Are these conditions ok?

The search will NOT perform if CompanyCode and BrandName are empty. (Flash message will be shown.)

Maximum number of results is always 20.

**Comment by timcu** [comment]
Sounds good to me
