### ISSUE TITLE
Footer to show what version of excel file is in database

### ISSUE THREAD

**Issue by timcu** [timcu/sas-select#40]
For example:

Software provided by bpss. Version 0.0.11. Database sas-schedule-1-july-2019-full

**Comment by chayawit** [comment]
How can we keep track of the excel file name? Can we use database or version.py?

**Comment by timcu** [comment]
I recommend database. When deployed, version.py is in a location which is not writable from the app. There is an instance folder which is writable and so you could store a text file there in a similar style to version.py. However, I think it will be beneficial to have a table which logs when the database has been updated from the spreadsheet. I think the table should have the following fields

1. primary key, 64 bit integer should be fine
2. excel file name used
3. date that excel file was inserted successfully into database
4. date that web site was last scraped to see if new file exists but found the same file as this one

When init-db is called, the last record in the table is checked to see when site was last scraped. 

If it was today then init-db aborts without downloading excel file or updating database. If not then scrape the site again. If it still has the same name, then update the date scraped field in database and abort. If new name then create new record in table, download table, insert data into tbl_products. If successful then set the date successful field in database and date scraped field.

To override the behaviour
1. set date scraped field to null to force scrape even if previous scrape was today
2. set date successful field to null to force excel download even if file name still the same 

In the future we may add automatic running of init-db for every request. It will be fast because it will only scrape the gov website once a day, and it will only download excel file every month or two when a new one is available.

**Comment by chayawit** [comment]
Can I rename the database from db_products.sqlite to sas.sqlite or sas_select.sqlite or do you suggest any other names?

Should the new table named tbl_data_reading?

I notice that every time the app starts, tbl_products is dropped and re-created. Do we expect the same behaviour for the new table?

Maybe I misunderstood that tbl_products is re-created.

**Comment by timcu** [comment]
If you want to you can rename db. When creating new db, should check for old db and delete as it is no longer required.

I didn't think tbl_products is dropped and recreated each time app starts. How have you noticed it?

**Comment by chayawit** [comment]
My bad. I saw `app.cli.add_command(init_db_command)` and thought it is called every time app starts.

**Comment by timcu** [comment]
`cli` is for command line interpreter and is how you set up commands which work from the command line.

**Comment by chayawit** [comment]
I would like make the success message of /init-db dynamic, not just "Database updated". For example, it could be "Database wasn't updated because there was no new file." or "Database wasn't updated because the last scrape was today."

My question is how should I pass the message from datasheet.py to init.py. Should `datasheet.init_db()` return string or maybe the message could be kept in `g`?

**Comment by timcu** [comment]
Return a str
