### ISSUE TITLE
Needs ACSA branding rather than QSA branding

### ISSUE THREAD

**Issue by timcu** [timcu/sas-select#42]
There is nothing specific to Queensland in this web app so can brand it with Australian Council of Stoma Associations branding. http://australianstoma.com.au/

**Comment by chayawit** [comment]
I suppose there are 3 changes to make, i.e., title, favicon and logo?

Page title is currently `QLD Stoma Appliance Schedule Selector - {{ page_title }}`.

Is it okay to change to `{{ page_title }} - Stoma Appliance Scheme Selector - Australian Council of Stoma Associations`?

For logo I'm sure we can use this.
![ACSA-Logo-rs](https://user-images.githubusercontent.com/13401471/61579990-d3b5c700-ab36-11e9-971a-8f33591767f5.png)

I used a favicon generator website but it doesn't look very nice. -> ![favicon1](https://user-images.githubusercontent.com/13401471/61580003-ffd14800-ab36-11e9-9881-7b9213627124.png)

Can we use ![favicon2](https://user-images.githubusercontent.com/13401471/61580004-02cc3880-ab37-11e9-89e3-bfe2ab0be918.png) or ![favicon3](https://user-images.githubusercontent.com/13401471/61580178-fd6fed80-ab38-11e9-840c-7d0a474c62e2.png) instead?

**Comment by timcu** [comment]
Your suggestions are good @chayawit . I have been looking up requirements for favicons and it looks like higher resolution are OK. I prefer the one with the circle. Make the background in the circle non-transparent so it looks good on light tabs and dark tabs.

**Comment by chayawit** [comment]
> it looks like higher resolution are OK

Could you please clarify this?

I thought favicons can be only 16px x 16px?

**Comment by timcu** [comment]
I think newer browsers can handle higher resolution but you should be able to test it. It only has to work in the latest browsers. The main reason for providing a favicon is to stop the log files filling up with file not found error messages. Every time someone visits a web page their web browser requests a favicon. We just have to provide one otherwise an error message goes in the logs making it harder to notice the real errors. So if you have a favicon which works in your browser, then that is good enough for me.

**Comment by chayawit** [comment]
> So if you have a favicon which works in your browser, then that is good enough for me.

But I use IE6. jks

**Comment by chayawit** [comment]
Tested using the logo as favicon an it works great. I will just have to fill white color inside the circle.
