### ISSUE TITLE
format_price raises TypeError exception with str

### ISSUE THREAD

**Issue by timcu** [timcu/sas-select#47]
If a `str` such as the empty `str` `""` is passed to the function format_price it crashes app. We are currently testing for None but not testing for str.

    File "/Users/tim/github/sas-select/sas_select/__init__.py", line 134, in format_price
    elif price >= 0:
    TypeError: '>=' not supported between instances of 'str' and 'int'

This currently doesn't occur because of data in database but could occur if a change is made to method populating database from excel spreadsheet

**Comment by chayawit** [comment]
If str is passed to format_price, should we return the str back?

Because the str could have already been properly formatted.

**Comment by timcu** [comment]
Yes. That sounds like a good idea.
