### ISSUE TITLE
Display entitlement in packs per month/year

### ISSUE THREAD

**Issue by timcu** [timcu/sas-select#5]
In the Medicare Entitlement, display the medicare entitlement in packs (as well as the original format eg 90m). If the entitlement is 90m and the pack size is 30 then display entitlement as 3 packs. If the entitlement is 60m and the pack size is 50 then display entitlement as 1 pack. Users mostly can’t order partial packs. The one case they can is if the pack size exceeds the entitlement. For example entitlement is 5m and pack size is 10 then they can order 1 pack but it has to last them 2 months.

**Comment by chayawit** [comment]
Entitlement is currently shown only at the viewproduct page. Should it be shown on the listproducts page as well?

Should the calculation be done when each product is inserted to the database or only at fetching for each time it's viewed?

**Comment by timcu** [comment]
I think entitlement can be calculated at time of viewing. This will reduce the amount of storage required (not really an issue), avoid storing same data in two formats which can get out of sync, and it won't take long to calculate. According to client it only needs to be shown on the viewproduct page.

**Comment by chayawit** [comment]
> For example entitlement is 5m and pack size is 10 then they can order 1 pack but it has to last them 2 months.

Do we have to actually do anything about the restriction of giving only once for 2 months?
Is it enough to just show '1'? Or maybe '1 (every 2 months)'?

**Comment by timcu** [comment]
I would like to see "1 pack per 2 months"

**Comment by timcu** [comment]
Fixed in PR #37
